//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCurdMD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public string CompanyName { get; set; }
        public string Designation { get; set; }
        public string ServicePeriod { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
